Repository Qowaiv/qowaiv-analyzers, pull requests merged in 2024-07, with the labels that each got.

#38 FN QW0008: Properties where not considered to decide if a struct had a well defined empty state
  specs/Qowaiv.CodeAnalysis.Specs/Cases/DefinePropertiesAsNotNullable.svo.cs
  specs/Qowaiv.CodeAnalysis.Specs/Qowaiv.CodeAnalysis.Specs.csproj
  src/Qowaiv.CodeAnalysis.CSharp/Qowaiv.CodeAnalysis.CSharp.csproj
  src/Qowaiv.CodeAnalysis.CSharp/Rules/DefinePropertiesAsNotNullable.cs
Labels: FN

#39 New Rule: Use Qowaiv decimal rounding
  Qowaiv.Analyzers.sln
  README.md
  rules/QW0013.md
  specs/Qowaiv.CodeAnalysis.Specs/Cases/UseQowaivDecimalRounding.Fixed.cs
  specs/Qowaiv.CodeAnalysis.Specs/Cases/UseQowaivDecimalRounding.ToFix.cs
  specs/Qowaiv.CodeAnalysis.Specs/Cases/UseQowaivDecimalRounding.cs
  specs/Qowaiv.CodeAnalysis.Specs/Fixes/Seal_class.cs
  specs/Qowaiv.CodeAnalysis.Specs/Fixes/Use_Qowaiv_Round_Extensions.cs
  specs/Qowaiv.CodeAnalysis.Specs/Rules/Use_Qowaiv_Decimal_Rounding.cs
  src/Qowaiv.CodeAnalysis.CSharp/CodeFixes/UseQowaivRoundExtensions.cs
  src/Qowaiv.CodeAnalysis.CSharp/Qowaiv.CodeAnalysis.CSharp.csproj
  src/Qowaiv.CodeAnalysis.CSharp/Rule.cs
  src/Qowaiv.CodeAnalysis.CSharp/Rules/UseQowaivDecimalRounding.cs
  src/Qowaiv.CodeAnalysis.CSharp/SystemType.Instances.cs
  src/Qowaiv.CodeAnalysis.CSharp/SystemType.cs
Labels: feature

#40 New Rule: Define global using statements separately
  Qowaiv.Analyzers.sln
  README.md
  rules/QW0014.md
  specs/Qowaiv.CodeAnalysis.Specs/Cases/DefineGlobalUsingStatementsSeparately.GlobalUsings.cs
  specs/Qowaiv.CodeAnalysis.Specs/Cases/DefineGlobalUsingStatementsSeparately.cs
  specs/Qowaiv.CodeAnalysis.Specs/Qowaiv.CodeAnalysis.Specs.csproj
  specs/Qowaiv.CodeAnalysis.Specs/Rules/Define_global_using_statements_separately.cs
  src/Qowaiv.CodeAnalysis.CSharp/Qowaiv.CodeAnalysis.CSharp.csproj
  src/Qowaiv.CodeAnalysis.CSharp/Rule.cs
  src/Qowaiv.CodeAnalysis.CSharp/Rules/DefineGlobalUsingStatementsSeparately.cs
Labels: feature

#41 Define global using statements in single file
  Qowaiv.Analyzers.sln
  README.md
  rules/QW0015.md
  specs/Qowaiv.CodeAnalysis.Specs/Cases/DefineGlobalUsingStatementsInSingleFile.cs
  specs/Qowaiv.CodeAnalysis.Specs/Cases/GlobalUsings.cs
  specs/Qowaiv.CodeAnalysis.Specs/Rules/Define_global_using_statements_in_single_file.cs
  src/Qowaiv.CodeAnalysis.CSharp/Extensions/Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext.cs
  src/Qowaiv.CodeAnalysis.CSharp/Extensions/Microsoft.CodeAnalysis.ISymbol.cs
  src/Qowaiv.CodeAnalysis.CSharp/Qowaiv.CodeAnalysis.CSharp.csproj
  src/Qowaiv.CodeAnalysis.CSharp/README.md
  src/Qowaiv.CodeAnalysis.CSharp/Rule.cs
  src/Qowaiv.CodeAnalysis.CSharp/Rules/DefineGlobalUsingStatements.cs
  src/Qowaiv.CodeAnalysis.CSharp/Rules/DefineGlobalUsingStatementsInSingleFile.cs
  src/Qowaiv.CodeAnalysis.CSharp/Rules/DefineGlobalUsingStatementsSeparately.cs
  src/Qowaiv.CodeAnalysis.CSharp/SystemType.cs
Labels: feature

#42 Fix typo's and missing text
  rules/QW0003.md
  rules/QW0004.md
  rules/QW0015.md
  specs/Qowaiv.CodeAnalysis.Specs/Cases/DefinePropertiesAsNotNullable.generics.cs
  specs/Qowaiv.CodeAnalysis.Specs/Cases/ParseShouldNotFail.cs
  specs/Qowaiv.CodeAnalysis.Specs/Cases/SealClasses.Records.cs
  specs/Qowaiv.CodeAnalysis.Specs/Cases/SealClasses.cs
  specs/Qowaiv.CodeAnalysis.Specs/Rules/Only_unsealed_concrete_classes_can_be_inheritable.cs
  specs/Qowaiv.CodeAnalysis.Specs/Rules/Seal_classes.cs
  src/Qowaiv.CodeAnalysis.CSharp/Extensions/System.String.cs
  src/Qowaiv.CodeAnalysis.CSharp/Rule.cs
Labels: documentation, enhancement

#43 FP: QW0015: The FilePath is more commonly a full path
  specs/Qowaiv.CodeAnalysis.Specs/Rules/Define_global_using_statements_in_single_file.cs
  src/Qowaiv.CodeAnalysis.CSharp/Qowaiv.CodeAnalysis.CSharp.csproj
  src/Qowaiv.CodeAnalysis.CSharp/Rules/DefineGlobalUsingStatementsInSingleFile.cs
Labels: FP
